### ISSUE TITLE
How to extend to inner_product?

### ISSUE THREAD

**Issue by Leslie-Chung** [gaoj0017/ADSampling#3]
When the metric is inner product, what should be returned in Algorithm 1:ADSampling. The code I wrote is as follows:
```C
    float dist_comp(const float &dis, const void *data, const void *query, const float data_size, const float query_size, 
                    float res = 0, int i = 0)
    {

        float r2 = 2.0f - 2 * dis / (data_size * query_size); 
       
        float y = 0;
        float *q = (float *)query;
        float *d = (float *)data;

        while (i < D)
        {
            // It continues to sample additional delta_d dimensions.
            int check = std::min(delta_d, D - i);
            i += check;
            for (int j = 1; j <= check; j++)
            {
                float t = *d - *q; // oi - qi
                res += *d * *q; // 内积
                d++;
                q++;
                y += t * t; // 欧氏距离
            }
            if (y >= r2 * ratio(D, i))
            {
                return -2;
            }
        }
        return -res;
    }
```
where data and query is the normalized from transformed vector, data_size is the magnitude of original data, query_size is the magnitude of original query. It returns -2 means the inner product of original vectors is smaller than r(i.e. dis). Otherwise, it returns the inner product of normalized vectors, I will multiply data_size  and query_size later to restore the inner product of original vectors. Is that right?

**Comment by gaoj0017** [comment]
The question has been resolved via emails.
